//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 12:16:27 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://health.ds/soa/soa-endpoints", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ds.health.soa.soa_endpoints;
