//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.26 at 12:22:54 AM EET 
//


package ds.health.soa.soa_endpoints;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ds.health.soa.soa_endpoints package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ds.health.soa.soa_endpoints
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPatientRecommendationResponse }
     * 
     */
    public GetPatientRecommendationResponse createGetPatientRecommendationResponse() {
        return new GetPatientRecommendationResponse();
    }

    /**
     * Create an instance of {@link SetPatientRecommendationResponse }
     * 
     */
    public SetPatientRecommendationResponse createSetPatientRecommendationResponse() {
        return new SetPatientRecommendationResponse();
    }

    /**
     * Create an instance of {@link GetMedicationIntakeRequest }
     * 
     */
    public GetMedicationIntakeRequest createGetMedicationIntakeRequest() {
        return new GetMedicationIntakeRequest();
    }

    /**
     * Create an instance of {@link GetPatientRecommendationRequest }
     * 
     */
    public GetPatientRecommendationRequest createGetPatientRecommendationRequest() {
        return new GetPatientRecommendationRequest();
    }

    /**
     * Create an instance of {@link GetPatientActivityRequest }
     * 
     */
    public GetPatientActivityRequest createGetPatientActivityRequest() {
        return new GetPatientActivityRequest();
    }

    /**
     * Create an instance of {@link SetPatientRecommendationRequest }
     * 
     */
    public SetPatientRecommendationRequest createSetPatientRecommendationRequest() {
        return new SetPatientRecommendationRequest();
    }

    /**
     * Create an instance of {@link GetMedicationIntakeResponse }
     * 
     */
    public GetMedicationIntakeResponse createGetMedicationIntakeResponse() {
        return new GetMedicationIntakeResponse();
    }

    /**
     * Create an instance of {@link MedicationIntakeList }
     * 
     */
    public MedicationIntakeList createMedicationIntakeList() {
        return new MedicationIntakeList();
    }

    /**
     * Create an instance of {@link GetPatientActivityResponse }
     * 
     */
    public GetPatientActivityResponse createGetPatientActivityResponse() {
        return new GetPatientActivityResponse();
    }

    /**
     * Create an instance of {@link PatientActivityList }
     * 
     */
    public PatientActivityList createPatientActivityList() {
        return new PatientActivityList();
    }

    /**
     * Create an instance of {@link PatientActivity }
     * 
     */
    public PatientActivity createPatientActivity() {
        return new PatientActivity();
    }

    /**
     * Create an instance of {@link MedicationIntake }
     * 
     */
    public MedicationIntake createMedicationIntake() {
        return new MedicationIntake();
    }

}
